# Generated by Django 5.2 on 2025-06-03 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_perfil_amigos_perfil_biografia_alter_perfil_foto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amistad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceptada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_enviadas', to=settings.AUTH_USER_MODEL)),
                ('para_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amistades_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('de_usuario', 'para_usuario')},
            },
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
