# Generated by Django 5.2 on 2025-07-07 17:40

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_amistad_delete_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='amigos',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/default.jpg', upload_to=users.models.ruta_foto_perfil),
        ),
    ]
