# Generated by Django 5.2 on 2025-07-17 11:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_perfil_amigos_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.ruta_foto_perfil),
        ),
    ]
