# Generated by Django 5.2 on 2025-07-18 10:59

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_perfil_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/default.jpeg', upload_to=users.models.ruta_foto_perfil),
        ),
    ]
