# Generated by Django 5.2 on 2025-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_perfil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='altura',
            field=models.FloatField(blank=True, help_text='Altura en cm', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='edad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='objetivo',
            field=models.CharField(blank=True, choices=[('deficit', 'Déficit calórico'), ('mantenimiento', 'Mantenimiento'), ('superavit', 'Superávit calórico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='peso',
            field=models.FloatField(blank=True, help_text='Peso en kg', null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=10, null=True),
        ),
    ]
