# Generated by Django 5.2 on 2025-08-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_perfil_altura_perfil_edad_perfil_objetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivel_actividad',
            field=models.CharField(choices=[('sedentario', 'Sedentario'), ('ligero', 'Ligero'), ('moderado', 'Moderado'), ('activo', 'Activo'), ('muy_activo', 'Muy Activo')], default='sedentario', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='altura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='objetivo',
            field=models.CharField(choices=[('deficit', 'Déficit calórico'), ('mantenimiento', 'Mantenimiento'), ('superavit', 'Superávit calórico')], default='mantenimiento', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, null=True),
        ),
    ]
