# Generated by Django 5.2 on 2025-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_perfil_nivel_actividad_alter_perfil_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/default.jpeg', null=True, upload_to='perfiles'),
        ),
    ]
