# Generated by Django 5.2 on 2025-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('allergy', 'Alergia'), ('avoid', 'Evitar')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='preferencias',
            field=models.ManyToManyField(blank=True, to='users.preference'),
        ),
    ]
