# Generated by Django 5.2 on 2025-09-12 18:04

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_preference_perfil_preferencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='preferencias',
        ),
        migrations.AddField(
            model_name='perfil',
            name='alergias',
            field=models.TextField(blank=True, default='', help_text='Separadas por comas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ingredientes_a_evitar',
            field=models.TextField(blank=True, default='', help_text='Separados por comas'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='tags_a_evitar',
            field=models.TextField(blank=True, default='', help_text='Separados por comas'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='perfiles/default.jpeg', null=True, upload_to=users.models.ruta_foto_perfil),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
    ]
