# Generated by Django 5.2 on 2025-08-29 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0010_platopersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoRecetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('privacidad', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], default='publico', max_length=10)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_creados', to=settings.AUTH_USER_MODEL)),
                ('miembros', models.ManyToManyField(related_name='grupos', through='grupos.GrupoMiembro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='grupomiembro',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grupos.gruporecetas'),
        ),
        migrations.AlterUniqueTogether(
            name='grupomiembro',
            unique_together={('usuario', 'grupo')},
        ),
        migrations.CreateModel(
            name='RecetaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='grupos.gruporecetas')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='recipes.receta')),
            ],
            options={
                'unique_together': {('grupo', 'receta')},
            },
        ),
    ]
