# Generated by Django 5.2 on 2025-07-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='calorias',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='carbohidratos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='grasas',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receta',
            name='proteinas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
