# Generated by Django 5.2 on 2025-07-16 16:11

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_receta_calorias_receta_carbohidratos_receta_grasas_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='receta',
            name='dificultad',
            field=models.CharField(blank=True, choices=[('fácil', 'Fácil'), ('media', 'Media'), ('difícil', 'Difícil')], max_length=20),
        ),
        migrations.AddField(
            model_name='receta',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='receta',
            name='tiempo_preparacion',
            field=models.PositiveIntegerField(blank=True, help_text='Minutos', null=True),
        ),
    ]
