# Generated by Django 5.2 on 2025-07-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_receta_categoria_receta_dificultad_receta_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='categoria',
        ),
    ]
