# Generated by Django 5.2 on 2025-07-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_remove_receta_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='tipo_cocina',
            field=models.CharField(choices=[('italiana', 'Italiana'), ('mexicana', 'Mexicana'), ('asiatica', 'Asiática'), ('china', 'China'), ('japonesa', 'Japonesa'), ('india', 'India'), ('tailandesa', 'Tailandesa'), ('coreana', 'Coreana'), ('española', 'Española'), ('francesa', 'Francesa'), ('griega', 'Griega'), ('alemana', 'Alemana'), ('americana', 'Americana'), ('marroqui', 'Marroquí'), ('libanesa', 'Libanesa'), ('peruana', 'Peruana'), ('argentina', 'Argentina'), ('brasilena', 'Brasileña'), ('vegana', 'Vegana'), ('vegetariana', 'Vegetariana'), ('sin_gluten', 'Sin gluten'), ('rapida', 'Rápida'), ('fusion', 'Fusión'), ('otra', 'Otra')], default='otra', max_length=100),
            preserve_default=False,
        ),
    ]
