# Generated by Django 5.2 on 2025-08-19 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_receta_tipo_cocina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='tipo_cocina',
        ),
        migrations.AddField(
            model_name='receta',
            name='porciones',
            field=models.PositiveIntegerField(default=1, help_text='Número de porciones de la receta'),
        ),
        migrations.CreateModel(
            name='PlanDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del plan, por ejemplo 'Lunes', 'Martes', etc.", max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('calorias_totales', models.FloatField(default=0)),
                ('proteinas_totales', models.FloatField(default=0)),
                ('grasas_totales', models.FloatField(default=0)),
                ('carbohidratos_totales', models.FloatField(default=0)),
                ('recetas', models.ManyToManyField(related_name='planes', to='recipes.receta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_diarios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
