# Generated by Django 5.2 on 2025-08-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_receta_tipo_cocina_receta_porciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('grasas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos_personalizados', to='recipes.plandiario')),
            ],
        ),
    ]
