# Generated by Django 5.2 on 2025-09-11 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_plansemanal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansemanal',
            name='planes_diarios',
        ),
        migrations.AddField(
            model_name='plandiario',
            name='plan_semanal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planes_diarios', to='recipes.plansemanal'),
        ),
        migrations.AlterField(
            model_name='plandiario',
            name='fecha',
            field=models.DateField(),
        ),
    ]
