# Generated by Django 5.2 on 2025-09-12 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_plansemanal_planes_diarios_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platopersonalizado',
            name='plan',
        ),
        migrations.AddField(
            model_name='plandiario',
            name='platos_personalizados',
            field=models.ManyToManyField(blank=True, related_name='planes_diarios', to='recipes.platopersonalizado'),
        ),
        migrations.AddField(
            model_name='platopersonalizado',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='platos_personalizados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
